### ISSUE TITLE
jni.h : No such file or directory

### ISSUE THREAD

**Issue by PvdBerg1998** [rust-windowing/android-rs-glue#163]
I just set up a linux virtualbox with the android sdk/ndk etc. When I try to run `cargo apk build`, the following error is printed:
```
/home/pim/android-ndk-r16/sources/android/native_app_glue/android_native_app_glue.c:18:17: fatal error: jni.h: No such file or directory
 #include <jni.h>
                 ^
compilation terminated.
error: process didn't exit successfully: `/home/pim/android-ndk-r16/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-gcc /home/pim/android-ndk-r16/sources/android/native_app_glue/android_native_app_glue.c -c -o /home/pim/GitHub/project/target/android-artifacts/arm-linux-androideabi/android_native_app_glue.o --sysroot /home/pim/android-ndk-r16/platforms/android-18/arch-arm` (exit code: 1)
```

Any idea why? I've set `ANDROID_HOME` and `NDK_HOME` to the corresponding root directories.

**Comment by tomaka** [comment]
Does the `/home/pim/android-ndk-r16/platforms/android-18/arch-arm/include` directory contain a `jni.h`?

**Comment by PvdBerg1998** [comment]
Nope, the directory does not even exist. There is one inside `home/pim/android-ndk-r16/sysroot/usr/include/` though.

**Comment by tomaka** [comment]
And does `/home/pim/android-ndk-r16/platforms/android-18/arch-arm` contain any directory at all (eg. `lib`)?

**Comment by PvdBerg1998** [comment]
Yes, `usr`.

**Comment by tomaka** [comment]
Well, what does `usr` contain? Does it contain `include` by chance?

**Comment by PvdBerg1998** [comment]
No, only a few `.so` and `.o` files.

**Comment by speaker73** [comment]
Hello. What version of NDK you have? I have this problem with 16 NDK. But working of 15 is good.

15 NDK(android-ndk-r15c)
16 NDK(android-ndk-r16)

**Comment by Cyres** [comment]
I have the same problem and searched a bit: r15 defaults to unified sysroots, the platform specific sysroots are deprecated. r16 removed them entirely.

**Comment by photex** [comment]
Seems like updating this should be a priority. The fix would be compatible back to r14.

https://github.com/golang/mobile/commit/3ef91fec25dd7d4bdd8075088e44cbf236a84e46#diff-bb8d1c5d57784117597766608f27e20c

https://github.com/bazelbuild/bazel/issues/4068

**Comment by siriux** [comment]
@photex can you share your changes to cargo-apk?

**Comment by siriux** [comment]
I tried to fix this, and I got a little bit further. The only error missing for me is the last one:

example-1fc8fdb63a0d034c.example1.rcgu.o: requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC

Do you have any idea where can I provide the -fPIC option? I've been trying but I don't find where are generated the ld parameters.

**Comment by photex** [comment]
Maybe here: https://github.com/tomaka/android-rs-glue/blob/master/cargo-apk/linker.rs

**Comment by siriux** [comment]
I already tried there, but is not working.

Anyway, is really weird that just changing the paths we get an error related to relocation types, maybe there is something else going on.

**Comment by siriux** [comment]
I've found the problem, it's the provided -pie option. If you run cargo with this enviroment variable defined it works: RUSTFLAGS='-C relocation-model=dynamic-no-pic -C link-args=-no-pie'

Probably there is a better option to activate it.

Now, let's try to make it work, because I still get some errors on the java part.

**Comment by wmww** [comment]
Any updates? Just ran into this issue. Is there a working fix yet or should I downgrade my NDK?

**Comment by francesca64** [comment]
@wmww downgrading to NDK r15c works fine, and is fairly quick and easy. https://developer.android.com/ndk/downloads/older_releases

This repo isn't very active, and I'm too busy elsewhere in the ecosystem to do anything about it, so it could be a while before this is really fixed.

**Comment by philip-alldredge** [comment]
This should no longer be an issue with the current cargo apk nightly or docker image. Recommend closing.
