### ISSUE TITLE
Could not execute 'gradle'

### ISSUE THREAD

**Issue by nelyubin-ev** [rust-windowing/android-rs-glue#164]
![image](https://user-images.githubusercontent.com/3295141/33265024-ab9a3822-d3bb-11e7-9ebc-1dc21c681806.png)

As you can see, cmd can execute "gradle" command, but cargo-apk cannot.

**Comment by tomaka** [comment]
It probably needs to be `gradle.exe` or something, I suppose?

**Comment by nelyubin-ev** [comment]
There is no "gradle.exe" in folder. Only "gradle" & "gradle.bat". 
Doing step-by-step from "Manual Usage" (from https://github.com/tomaka/android-rs-glue/blob/master/README.md)

**Comment by jrb467** [comment]
I've been having the same issue. I noticed the source for "cargo-apk" doesn't match the actual version on crates.io (it prints out something different than it should when it can't find gradle).

**Comment by jrb467** [comment]
I'm pretty sure if you update the version on crates, we can just set CARGO_APK_GRADLE_COMMAND to "gradle.bat" (or "gradle.cmd", that's what it is if you install through Scoop) and it *should* work

**Comment by jrb467** [comment]
With new version bump, build works for me when passing fully-qualified command name to CARGO_APK_GRADLE_COMMAND (just "gradle.bat" didn't work, had an issue loading GradleMain). If this works for @nelyubin-ev lets go ahead and close this.

**Comment by tomaka** [comment]
Cargo-apk should try to autodetect that though.

**Comment by jrb467** [comment]
I don't think it's an issue in cargo-apk, from what I can tell. Just that rust's process spawning on windows has trouble with non-.exe files unless they're explicitly qualified. I'll link some of the issues in rust-lang about this once I'm at an actual computer.

**Comment by mb64** [comment]
Fixed by #223, which removes Gradle.
