### ISSUE TITLE
MultipleUsesSdk in src/ops/build.rs

### ISSUE THREAD

**Issue by alanpoon** [rust-windowing/android-rs-glue#175]
I got the following error due to the commit d726f1e1b13ae54674edc4843b7bb8e7d3499279.
artifacts/app/src/main/AndroidManifest.xml:9: Error: There should only be a single <uses-sdk> element in the manifest: merge these together [MultipleUsesSdk]
    <uses-sdk android:minSdkVersion="18" />
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/project/target/android-artifacts/app/src/main/AndroidManifest.xml:8: Also appears here

   Explanation for issues of type "MultipleUsesSdk":
   The <uses-sdk> element should appear just once; the tools will not merge
   the contents of all the elements so if you split up the attributes across
   multiple elements, only one of them will take effect. To fix this, just
   merge all the attributes from the various elements into a single <uses-sdk>
   element.

**Comment by philip-alldredge** [comment]
This was fixed in d46f7ef8a4aeb71de286643e9b7d1582a5eca8a8. Recommend closing the issue.
