### ISSUE TITLE
Windows: ndk toolchain binaries/scripts have file extensions

### ISSUE THREAD

**Issue by robojumper** [rust-windowing/android-rs-glue#192]
https://github.com/tomaka/android-rs-glue/blob/14129667261c673c3bc355e0cf2e2895ec1cbddd/cargo-apk/src/ops/build.rs#L76-L78 doesn't work on Windows: `ar` is a `.exe`, while `gcc` and `g++` are `.cmd`s.

**Comment by shijunti19** [comment]
me too windows10

**Comment by mb64** [comment]
This should be fixed by #223.
