### ISSUE TITLE
windows: 1314 error

### ISSUE THREAD

**Issue by Nirklav** [rust-windowing/android-rs-glue#194]
Hello!

I have a simple project that works. But it works only without assets and resources folders. If i'm specify them in the cargo.toml then i receive an "os error 1314".

Where i can give permissions for these folders?

PS. If i run intelliJ Idea from administrator user, then all works fine.

**Comment by philip-alldredge** [comment]
@Nirklav can you check whether this is still an issue with the currently git version?

**Comment by Nirklav** [comment]
With current git repository version i can't reproduce this issue, thanks!
