### ISSUE TITLE
Rust 2018?

### ISSUE THREAD

**Issue by ZeGentzy** [rust-windowing/android-rs-glue#202]
This doesn't seam to come with a recent version of rust.

See https://circleci.com/gh/ZeGentzy/glutin/29#tests/containers/0: 
> warning: unused manifest key: package.edition

**Comment by mb64** [comment]
For the short term, #223 introduces a new Docker image with the updates.  However, for the long term,  there should probably be some automated way of updating it.  I will bring it up in #221, which seems to have discussion of CI.
