### ISSUE TITLE
Publish most recent version?

### ISSUE THREAD

**Issue by gw3583** [rust-windowing/android-rs-glue#204]
Hi, would it be possible to get the most recent version published?

I am currently building from source to get the support for the min sdk version specification, but it'd be great if that available in the installed version.

**Comment by jrmuizel** [comment]
@mb64 there have been a bunch of new changes to cargo-apk. Would it be possible to get a new release?

**Comment by jrmuizel** [comment]
Oh I see there's also #221

**Comment by mb64** [comment]
Thanks for the request and (accidentally) notifying me of the duplicate issues.  I'll close this in favor of #221.
