### ISSUE TITLE
cargo-apk install builds debug build

### ISSUE THREAD

**Issue by philip-alldredge** [rust-windowing/android-rs-glue#236]
Additionally, the install command needs to support the release flag.

**Comment by philip-alldredge** [comment]
@mb64 I can take a look at this. Adding here for tracking. This was observed when tracking down recent issues but this is not the cause of the issues.

**Comment by philip-alldredge** [comment]
After further investigation, it turns out that the release builds are working as expected. I have updated the issue accordingly. The only thing that needs to be fixed for this issue is the support for the release flag in the `install` command.

**Comment by philip-alldredge** [comment]
Another option would be to not support the `--release` flag but to rather build the release version by default. This would be more inline with how `cargo install` works.

**Comment by mb64** [comment]
Did #237 fix this?
