### ISSUE TITLE
`android:version` isn't a key for uses-feature

### ISSUE THREAD

**Issue by mb64** [rust-windowing/android-rs-glue#242]
Compiling the `advanced` example, it complains that attribute `android:version` isn't found.  This agrees with [the docs](https://developer.android.com/guide/topics/manifest/uses-feature-element).

The next question I have is why didn't CircleCI get this? This seems like it should've been caught by the tests.

**Comment by philip-alldredge** [comment]
In some cases `android:version` is an attribute for `uses-feature`. Look in the section regarding `android.hardware.vulkan.compute`.  The top part of the documentation is confusing and incomplete.

**Comment by mb64** [comment]
My bad – I was trying to compile for SDK 21 (those were just the tools I had downloaded), while Vulkan was added in SDK 24.
