### ISSUE TITLE
cargo apk build fails if ~/.android doesn't exist

### ISSUE THREAD

**Issue by jamienicol** [rust-windowing/android-rs-glue#252]
I've been updating our CI to use the latest cargo apk (from several months ago), and I noticed that the build was failing:

> error: process didn't exit successfully: `/usr/bin/keytool -genkey -v -keystore /builds/worker/.android/debug.keystore -storepass android -alias androidebugkey -keypass android -dname 'CN=Android Debug,O=Android,C=US' -keyalg RSA -keysize 2048 -validity 10000` (exit code: 1)

This is because as of #223 cargo-apk now attempts to sign the output apk, which is great, but the `.android` directory does not exist on our CI and we get this error.

I can reproduce the same error locally by deleting `~/.android`.

Adding a `mkdir .android` to our build script can work around this, but can/should this be fixed in cargo-apk instead?

**Comment by philip-alldredge** [comment]
The older gradle build probably was creating the android folder if it didn't exist. I don't see any reason why we shouldn't make the new build system work the same way.
